redis.host=localhost
redis.port=6379
redis.password=
# Thời gian chờ kết nối tối đa (milliseconds) — 2000ms = 2 giây
redis.timeout=2000
# Thời gian của OTP — 300 giây 
redis.ttl.otp=300
# Thời gian cache sản phẩm — 1800 giây
redis.ttl.product=1800
