redis.host=localhost
redis.port=6379
redis.password=
redis.timeout=2000
redis.pool.maxTotal=20
redis.pool.maxIdle=5
redis.pool.minIdle=1

# TTL tính bằng giây
redis.ttl.otp=300
redis.ttl.product=1800
